# Generated by Django 5.1.3 on 2024-11-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_atividade_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='gif_exercicio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
