# Generated by Django 5.1.3 on 2024-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_atividade_gif_exercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='dia_semana',
            field=models.CharField(max_length=30),
        ),
    ]
